export const Questions = [
    {
      prompt: "What is the port of HTTPS?",
      option1: "21",
      option2: "25",
      option3: "3306",
      option4: "443",
      asnwer: 4,
    },
    {
      prompt: "Which of this is not a programming language?",
      option1: "Python",
      option2: "JavaScript",
      option3: "MC-03",
      option4: "Java",
      asnwer: 3,
    },
    {
      prompt: "Which of this is not a javascript framework?",
      option1: "React",
      option2: "Angular",
      option3: "Vue",
      option4: "Java",
      asnwer: 4,
    },
    {
        prompt: "Which of this is not a PHP framework?",
        option1: "Symphony",
        option2: "PHP Cake",
        option3: "Vue",
        option4: "Laravel",
        asnwer: 3,
      },

      {
        prompt: "3. How do you represent data in JSON?",
        option1: "Metadata",
        option2: "Binary Data",
        option3: "Key-Value pairs ",
        option4: "Key-Object pairs",
        asnwer: 3,
      },
      {
        prompt: "What is the file extension commonly used for JSON files?",
        option1: "json",
        option2: "js",
        option3: "xml",
        option4: "txt",
        asnwer: 1,
      },
  ];